os: linux
dist: bionic

language: python
python: 3.8

jobs:
  include:
    - name: "Single Image Trial"
      install: pip install -r requirements.txt
      script:
        - python main.py -i images/adrian.png
        - python main.py -i images/neil_patrick_harris.png
        - python main.py -i images/samuel_l_jackson.png
    - name: "Lint"
      install: pip install black
      script: black main.py src --check
