os: linux
dist: bionic

language: python
python: 3.8
cache: pip

jobs:
  include:
    - name: "Single Image Test"
      install:
        - sudo apt-get install -y build-essential
        - sudo apt-get install -y cmake git pkg-config libopenblas-dev liblapack-dev libboost-python-dev
        - sudo apt-get install -y python-opencv dlib
      script:
        - python main.py -i data/single_images/adrian.png
        - python main.py -i data/single_images/neil_patrick_harris.png
        - python main.py -i data/single_images/samuel_l_jackson.png
    - name: "Lint"
      install: pip install black
      script: black main.py src --check
