os: linux
dist: bionic

language: python
python: 3.8

jobs:
  include:
    - name: "Single Image Test"
      install:
        - apt-get install -y python-opencv dlib
      script:
        - python main.py -i data/single_images/adrian.png
        - python main.py -i data/single_images/neil_patrick_harris.png
        - python main.py -i data/single_images/samuel_l_jackson.png
    - name: "Lint"
      install: pip install black
      script: black main.py src --check
